spring:
  application:
    name: payment-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments_db}
    username: ${DB_USERNAME:payments_user}
    password: ${DB_PASSWORD:payments_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.payments.transaction.domain"
    topic: payment-events
    group-id: payment-group

flyway:
  enabled: false

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      payment-db:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      payment-db:
        max-attempts: 3
        wait-duration: 1s
  ratelimiter:
    instances:
      payment-api:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 0s
api:
  info:
    title: Payment Service API
    description: REST API for processing payments
    version: 1.0.0
    contact-name: Sebastian
    contact-email: seby_buga@email.com
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

auth:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}